[project]
name = "fastapi_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.15.1",
    "fastapi>=0.115.11",
    "uvicorn[standard]>=0.34.0",
]
